### ISSUE TITLE
Got an error when running the commands

### ISSUE THREAD

**Issue by billbazza** [harvp0wn/pihole-block-unblock#8]
Hi there,

I always get the following error:

 sudo bash pihole-block.sh
  [i] No results found for --wild within the block lists
Unknown query option specified
Try 'pihole -q --help' for more information.
  [✓] Restarting DNS server

I tried changing --wild to --regex and -b but have the same results. Any ideas?

**Comment by harvp0wn** [comment]
Thank you for the feedback. I will look into this when I have a chance.

**Comment by billbazza** [comment]
Hi there, the problem was with the -q in the command.

**Comment by harvp0wn** [comment]
Thanks I will update it
